name: vtsapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:

  flutter:
    sdk: flutter
  firebase_auth: ^4.19.4
  intl: ^0.19.0
  cloud_firestore: ^4.17.2
  flutter_form_builder: ^9.2.1
  firebase_storage: ^11.7.4
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.1
  flutter_local_notifications: ^17.1.1
  shared_preferences: ^2.2.3
  external_app_launcher: ^4.0.0
  url_launcher: ^6.2.6
  firebase_app_check: ^0.2.2+4
  flutter_email_sender: ^6.0.3
  mailer: ^6.1.0
  firebase_database: ^10.5.7
  firebase_messaging: ^14.9.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/backunder3.png
    - images/kdu-logo.png
    - images/firstpg.png
    - images/kdu.png
    - images/dashboard.png
    - images/signin.png
    - images/usericon.png
    - images/vehicledashboard.jpg
    - images/bookingback.png
    - images/bookingfirst.jpg
    - images/available.jpg
    - images/vregi.png
    - images/signin3.jpg
    - images/availability.jpg
    - images/trackingimage.jpg
    - images/piclogin.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
